OOF.Microstructure.Create_From_ImageFile(filename='/home/nanohub/srehman6/data/results/1646501/grain.png', microstructure_name='grain.png', height=automatic, width=automatic)
OOF.Windows.Graphics.New()
OOF.Graphics_1.Toolbox.Pixel_Select.Point(source='grain.png:grain.png', points=[Point(9.53733333333,133.714666667)], shift=0, ctrl=0)
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='grain.png:grain.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(14.348,35.096)], shift=0, ctrl=0)
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='grain.png:grain.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(22.3657777778,20.664)], shift=0, ctrl=0)
OOF.PixelGroup.New(name='black_region', microstructure='grain.png')
OOF.PixelGroup.AddSelection(microstructure='grain.png', group='black_region')
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='grain.png:grain.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(37.5995555556,97.6346666667)], shift=0, ctrl=0)
OOF.PixelGroup.New(name='white_region', microstructure='grain.png')
OOF.PixelGroup.AddSelection(microstructure='grain.png', group='white_region')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_black_region')
OOF.Material.New(name='black_region_material', material_type='bulk')
OOF.Material.New(name='white_region_material', material_type='bulk')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_black_region(cijkl=IsotropicRank4TensorEnu(young=200000000000.0,poisson=0.3333333333333333))
OOF.Material.Add_property(name='black_region_material', property='Mechanical:Elasticity:Isotropic:youngs_black_region')
OOF.Property.Copy(property='Color', new_name='colour_black_region')
OOF.Property.Parametrize.Color.colour_black_region(color=Gray(value=0.0))
OOF.Material.Add_property(name='black_region_material', property='Color:colour_black_region')
OOF.Property.Copy(property='Color', new_name='colour_white_region')
OOF.Property.Parametrize.Color.colour_white_region(color=Gray(value=1.0))
OOF.Material.Add_property(name='white_region_material', property='Color:colour_white_region')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_white_region')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_white_region(cijkl=IsotropicRank4TensorEnu(young=100000000000.0,poisson=0.27))
OOF.Material.Add_property(name='white_region_material', property='Mechanical:Elasticity:Isotropic:youngs_white_region')
OOF.Material.Assign(material='white_region_material', microstructure='grain.png', pixels='white_region')
OOF.Material.Assign(material='black_region_material', microstructure='grain.png', pixels='black_region')
OOF.Skeleton.New(name='skeleton', microstructure='grain.png', x_elements=40, y_elements=40, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Skeleton.Modify(skeleton='grain.png:skeleton', modifier=Anneal(targets=AllNodes(),criterion=AverageEnergy(alpha=0.8),T=0.0,delta=1.0,iteration=FixedIteration(iterations=100)))
OOF.Skeleton.Modify(skeleton='grain.png:skeleton', modifier=SwapEdges(targets=AllElements(),criterion=AverageEnergy(alpha=0.8)))
OOF.Mesh.New(name='mesh', skeleton='grain.png:skeleton', element_types=['D2_2', 'T3_3', 'Q4_4'])
OOF.Subproblem.Field.Define(subproblem='grain.png:skeleton:mesh:default', field=Displacement)
OOF.Subproblem.Field.Activate(subproblem='grain.png:skeleton:mesh:default', field=Displacement)
OOF.Mesh.Field.In_Plane(mesh='grain.png:skeleton:mesh', field=Displacement)
OOF.Subproblem.Equation.Activate(subproblem='grain.png:skeleton:mesh:default', equation=Force_Balance)
OOF.Mesh.Boundary_Conditions.New(name='bc', mesh='grain.png:skeleton:mesh', condition=DirichletBC(field=Displacement,field_component='x',equation=Force_Balance,eqn_component='x',profile=ConstantProfile(value=0.0),boundary='right'))
OOF.Mesh.Boundary_Conditions.New(name='bc<2>', mesh='grain.png:skeleton:mesh', condition=DirichletBC(field=Displacement,field_component='y',equation=Force_Balance,eqn_component='y',profile=ConstantProfile(value=0.0),boundary='right'))
OOF.Subproblem.Field.Define(subproblem='grain.png:skeleton:mesh:default', field=Temperature)
OOF.Subproblem.Field.Activate(subproblem='grain.png:skeleton:mesh:default', field=Temperature)
OOF.Mesh.Field.In_Plane(mesh='grain.png:skeleton:mesh', field=Temperature)
OOF.Subproblem.Equation.Activate(subproblem='grain.png:skeleton:mesh:default', equation=Heat_Eqn)
OOF.Mesh.Boundary_Conditions.New(name='bc<3>', mesh='grain.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=1000.0),boundary='right'))
OOF.Mesh.Boundary_Conditions.New(name='bc<4>', mesh='grain.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=0.0),boundary='left'))
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_white_region')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_white_region(alpha=1.0, T0=0.0)
OOF.Material.Add_property(name='white_region_material', property='Couplings:ThermalExpansion:Isotropic:a_white_region')
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_black_region')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_black_region(alpha=1e-05, T0=0.0)
OOF.Material.Add_property(name='black_region_material', property='Couplings:ThermalExpansion:Isotropic:a_black_region')
OOF.Material.Assign(material='black_region_material', microstructure='grain.png', pixels='black_region')
OOF.Material.Assign(material='white_region_material', microstructure='grain.png', pixels='white_region')
OOF.Subproblem.Set_Solver(subproblem='grain.png:skeleton:mesh:default', solver_mode=BasicSolverMode(time_stepper=BasicStaticDriver(),matrix_method=BasicIterative(tolerance=1e-13,max_iterations=1000)))
OOF.Mesh.Set_Field_Initializer(mesh='grain.png:skeleton:mesh', field=Temperature, initializer=ConstScalarFieldInit(value=0.0))
OOF.Mesh.Set_Field_Initializer(mesh='grain.png:skeleton:mesh', field=Displacement, initializer=ConstTwoVectorFieldInit(cx=0.0,cy=0.0))
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_black_region')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_black_region(kappa=100)
OOF.Material.Add_property(name='black_region_material', property='Thermal:Conductivity:Isotropic:k_black_region')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_white_region')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_white_region(kappa=20)
OOF.Material.Add_property(name='white_region_material', property='Thermal:Conductivity:Isotropic:k_white_region')
OOF.Material.Assign(material='white_region_material', microstructure='grain.png', pixels='white_region')
OOF.Material.Assign(material='black_region_material', microstructure='grain.png', pixels='black_region')
OOF.Mesh.Solve(mesh='grain.png:skeleton:mesh', endtime=0.0)
OOF.Graphics_1.Layer.Hide(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Hide(n=4)
OOF.Graphics_1.Layer.Select(n=4)
OOF.Graphics_1.Layer.Hide(n=5)
OOF.Graphics_1.Layer.Select(n=5)
OOF.Graphics_1.Layer.Show(n=5)
OOF.Graphics_1.File.Close()
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_black_region(cijkl=IsotropicRank4TensorEnu(young=117000000000.0,poisson=0.3333333333333333))
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_black_region(alpha=5.1e-05, T0=0.0)
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_black_region(kappa=390)
OOF.Material.Assign(material='black_region_material', microstructure='grain.png', pixels='black_region')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_white_region(cijkl=IsotropicRank4TensorEnu(young=200000000000.0,poisson=0.27))
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_white_region(alpha=3.6e-05, T0=0.0)
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_white_region(kappa=41)
OOF.Material.Assign(material='white_region_material', microstructure='grain.png', pixels='white_region')
OOF.Mesh.Solve(mesh='grain.png:skeleton:mesh', endtime=0.0)
OOF.Windows.Graphics.New()
OOF.Graphics_1.Layer.Hide(n=4)
OOF.Graphics_1.Layer.Select(n=4)
OOF.Graphics_1.Layer.Hide(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Select(n=5)
OOF.LayerEditor.LayerSet.Edit(window='Graphics_1', layer_number=5)
OOF.LayerEditor.LayerSet.Add_Method(method=FilledContourDisplay(when=latest,what=getOutput('Field:Component',component='x',field=Displacement),where=getOutput('original'),min=automatic,max=automatic,levels=11,nbins=5,colormap=ThermalMap()))
OOF.LayerEditor.LayerSet.Send(window='Graphics_1')
OOF.LayerEditor.LayerSet.Add_Method(method=FilledContourDisplay(when=latest,what=getOutput('Field:Component',component='',field=Temperature),where=getOutput('original'),min=automatic,max=automatic,levels=11,nbins=5,colormap=ThermalMap()))
OOF.LayerEditor.LayerSet.Send(window='Graphics_1')
OOF.Graphics_1.Layer.Hide(n=7)
OOF.Graphics_1.Layer.Show(n=7)
OOF.Graphics_1.File.Save_Image(filename='/home/nanohub/srehman6/data/results/1646501/temp', overwrite=False)
OOF.Graphics_1.Layer.Hide(n=2)
OOF.Graphics_1.Layer.Select(n=2)
OOF.Graphics_1.Layer.Hide(n=1)
OOF.Graphics_1.Layer.Select(n=1)
OOF.Graphics_1.Layer.Show(n=2)
OOF.Graphics_1.Layer.Select(n=2)
OOF.Graphics_1.Layer.Hide(n=2)
OOF.Graphics_1.Layer.Show(n=1)
OOF.Graphics_1.Layer.Select(n=1)
OOF.Graphics_1.File.Save_Image(filename='/home/nanohub/srehman6/data/results/1646501/displacement', overwrite=False)
OOF.Graphics_1.Layer.Hide(n=1)
OOF.Graphics_1.File.Save_Image(filename='/home/nanohub/srehman6/data/results/1646501/mesh_after_sim', overwrite=False)
OOF.Graphics_1.File.Close()
