OOF.Microstructure.Create_From_ImageFile(filename='/home/nanohub/srehman6/data/results/1649566/Ti64.png', microstructure_name='Ti64.png', height=automatic, width=automatic)
OOF.Windows.Graphics.New()
OOF.PixelGroup.New(name='alpha', microstructure='Ti64.png')
OOF.PixelGroup.New(name='beta', microstructure='Ti64.png')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(170.037837838,122.581081081)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='beta')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(4.93513513514,12.2135135135)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='beta')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(10.3189189189,171.035135135)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(36.3405405405,166.548648649)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(21.0864864865,160.267567568)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(39.9297297297,150.397297297)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(13.0108108108,126.17027027)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(8.52432432432,109.121621622)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(4.03783783784,113.608108108)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(18.3945945946,98.3540540541)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(9.42162162162,87.5864864865)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(2.24324324324,66.9486486486)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(13.0108108108,36.4405405405)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(13.9081081081,9.52162162162)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(109.021621622,84.8945945946)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(32.7513513514,3.24054054054)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(70.4378378378,8.62432432432)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(109.918918919,22.0837837838)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(136.837837838,44.5162162162)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(144.913513514,163.856756757)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(149.4,7.72702702703)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(161.962162162,61.5648648649)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(202.340540541,119.889189189)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(214.005405405,31.0567567568)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(190.675675676,67.8459459459)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(181.702702703,50.7972972973)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(292.967567568,40.0297297297)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(214.005405405,31.9540540541)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(240.027027027,21.1864864865)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(259.767567568,8.62432432432)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(295.659459459,1.44594594595)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(342.318918919,-3.04054054054)], shift=0, ctrl=0)
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(325.27027027,171.932432432)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(345.010810811,8.62432432432)], shift=0, ctrl=0)
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(328.859459459,126.17027027)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(321.681081081,133.348648649)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(319.886486486,71.4351351351)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(342.318918919,25.672972973)], shift=0, ctrl=0)
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(318.989189189,88.4837837838)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(347.702702703,25.672972973)], shift=0, ctrl=0)
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(317.194594595,118.991891892)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='Ti64.png', group='alpha')
OOF.Material.New(name='alpha', material_type='bulk')
OOF.Material.New(name='beta', material_type='bulk')
OOF.Property.Copy(property='Color', new_name='colour_alpha')
OOF.Property.Parametrize.Color.colour_alpha(color=Gray(value=1.0))
OOF.Material.Add_property(name='alpha', property='Color:colour_alpha')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_alpha')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_alpha(cijkl=IsotropicRank4TensorEnu(young=92800000000.0,poisson=0.35))
OOF.Material.Add_property(name='alpha', property='Mechanical:Elasticity:Isotropic:youngs_alpha')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_alpha')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_alpha(kappa=7.6)
OOF.Material.Add_property(name='alpha', property='Thermal:Conductivity:Isotropic:k_alpha')
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_alpha')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_alpha(alpha=8.6e-06, T0=0.0)
OOF.Material.Add_property(name='alpha', property='Couplings:ThermalExpansion:Isotropic:a_alpha')
OOF.Material.Assign(material='alpha', microstructure='Ti64.png', pixels='alpha')
OOF.Property.Copy(property='Color', new_name='colour_beta')
OOF.Material.Add_property(name='beta', property='Color:colour_beta')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_beta')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_beta(cijkl=IsotropicRank4TensorEnu(young=75800000000.0,poisson=0.3333333333333333))
OOF.Material.Add_property(name='beta', property='Mechanical:Elasticity:Isotropic:youngs_beta')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_beta')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_beta(kappa=11.3)
OOF.Material.Add_property(name='beta', property='Thermal:Conductivity:Isotropic:k_beta')
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_beta')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_beta(alpha=1.18e-05, T0=0.0)
OOF.Material.Add_property(name='beta', property='Couplings:ThermalExpansion:Isotropic:a_beta')
OOF.Material.Assign(material='beta', microstructure='Ti64.png', pixels='beta')
OOF.Skeleton.New(name='skeleton', microstructure='Ti64.png', x_elements=40, y_elements=40, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Skeleton.Modify(skeleton='Ti64.png:skeleton', modifier=Anneal(targets=AllNodes(),criterion=AverageEnergy(alpha=0.8),T=0.0,delta=1.0,iteration=FixedIteration(iterations=100)))
OOF.Skeleton.Modify(skeleton='Ti64.png:skeleton', modifier=SwapEdges(targets=AllElements(),criterion=AverageEnergy(alpha=0.8)))
OOF.Skeleton.Modify(skeleton='Ti64.png:skeleton', modifier=Smooth(targets=AllNodes(),criterion=AverageEnergy(alpha=0.8),T=0.0,iteration=FixedIteration(iterations=50)))
OOF.Mesh.New(name='mesh', skeleton='Ti64.png:skeleton', element_types=['D2_2', 'T3_3', 'Q4_4'])
OOF.Subproblem.Field.Define(subproblem='Ti64.png:skeleton:mesh:default', field=Temperature)
OOF.Subproblem.Field.Define(subproblem='Ti64.png:skeleton:mesh:default', field=Displacement)
OOF.Subproblem.Field.Activate(subproblem='Ti64.png:skeleton:mesh:default', field=Displacement)
OOF.Subproblem.Field.Activate(subproblem='Ti64.png:skeleton:mesh:default', field=Temperature)
OOF.Mesh.Field.In_Plane(mesh='Ti64.png:skeleton:mesh', field=Temperature)
OOF.Mesh.Field.In_Plane(mesh='Ti64.png:skeleton:mesh', field=Displacement)
OOF.Subproblem.Equation.Activate(subproblem='Ti64.png:skeleton:mesh:default', equation=Heat_Eqn)
OOF.Subproblem.Equation.Activate(subproblem='Ti64.png:skeleton:mesh:default', equation=Force_Balance)
OOF.Mesh.Boundary_Conditions.New(name='bc', mesh='Ti64.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=0.0),boundary='left'))
OOF.Mesh.Boundary_Conditions.New(name='bc<2>', mesh='Ti64.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=1000.0),boundary='right'))
OOF.Mesh.Boundary_Conditions.New(name='bc<3>', mesh='Ti64.png:skeleton:mesh', condition=DirichletBC(field=Displacement,field_component='x',equation=Force_Balance,eqn_component='x',profile=ConstantProfile(value=0),boundary='left'))
OOF.Mesh.Boundary_Conditions.New(name='bc<4>', mesh='Ti64.png:skeleton:mesh', condition=DirichletBC(field=Displacement,field_component='x',equation=Force_Balance,eqn_component='x',profile=ConstantProfile(value=0),boundary='right'))
OOF.Mesh.Boundary_Conditions.Delete(mesh='Ti64.png:skeleton:mesh', name='bc<4>')
OOF.Mesh.Boundary_Conditions.New(name='bc<4>', mesh='Ti64.png:skeleton:mesh', condition=DirichletBC(field=Displacement,field_component='y',equation=Force_Balance,eqn_component='y',profile=ConstantProfile(value=0.0),boundary='left'))
OOF.Subproblem.Set_Solver(subproblem='Ti64.png:skeleton:mesh:default', solver_mode=BasicSolverMode(time_stepper=BasicStaticDriver(),matrix_method=BasicIterative(tolerance=1.73e-08,max_iterations=100000)))
OOF.Mesh.Set_Field_Initializer(mesh='Ti64.png:skeleton:mesh', field=Temperature, initializer=ConstScalarFieldInit(value=0.0))
OOF.Mesh.Set_Field_Initializer(mesh='Ti64.png:skeleton:mesh', field=Displacement, initializer=ConstTwoVectorFieldInit(cx=0.0,cy=0.0))
OOF.Mesh.Solve(mesh='Ti64.png:skeleton:mesh', endtime=0.0)
OOF.Graphics_1.Toolbox.Pixel_Select.Burn(source='Ti64.png:Ti64.png', local_flammability=0.1, global_flammability=0.2, color_space_norm='L1', next_nearest=False, points=[Point(138.632432432,24.7756756757)], shift=0, ctrl=0)
OOF.Graphics_1.Layer.Hide(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Hide(n=4)
OOF.Graphics_1.Layer.Select(n=4)
OOF.Graphics_1.Layer.Select(n=5)
OOF.LayerEditor.LayerSet.Edit(window='Graphics_1', layer_number=5)
OOF.LayerEditor.LayerSet.Add_Method(method=FilledContourDisplay(when=latest,what=getOutput('Flux:Invariant',invariant=MatrixTrace(),flux=Stress),where=getOutput('original'),min=automatic,max=automatic,levels=100,nbins=5,colormap=SpectralMap(saturation=1,value=1)))
OOF.LayerEditor.LayerSet.Send(window='Graphics_1')
