OOF.Microstructure.Create_From_ImageFile(filename='/home/nanohub/srehman6/data/results/1643665/grain.png', microstructure_name='grain.png', height=automatic, width=automatic)
OOF.Windows.Graphics.New()
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='grain.png:grain.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(24.7711111111,12.6462222222)], shift=0, ctrl=0)
OOF.PixelGroup.New(name='black_region', microstructure='grain.png')
OOF.PixelGroup.AddSelection(microstructure='grain.png', group='black_region')
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='grain.png:grain.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(55.2386666667,92.824)], shift=0, ctrl=0)
OOF.PixelGroup.New(name='white_region', microstructure='grain.png')
OOF.PixelGroup.AddSelection(microstructure='grain.png', group='white_region')
OOF.Material.New(name='white_region', material_type='bulk')
OOF.Material.New(name='black_region', material_type='bulk')
OOF.Property.Copy(property='Color', new_name='colour_black_region')
OOF.Property.Parametrize.Color.colour_black_region(color=Gray(value=0.0))
OOF.Material.Add_property(name='black_region', property='Color:colour_black_region')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_black_region')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_black_region(cijkl=IsotropicRank4TensorEnu(young=500000000000.0,poisson=0.33))
OOF.Material.Add_property(name='black_region', property='Mechanical:Elasticity:Isotropic:youngs_black_region')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_black_region')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_black_region(kappa=500)
OOF.Material.Add_property(name='black_region', property='Thermal:Conductivity:Isotropic:k_black_region')
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_black_region')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_black_region(alpha=1000, T0=0.0)
OOF.Material.Add_property(name='black_region', property='Couplings:ThermalExpansion:Isotropic:a_black_region')
OOF.Material.Remove_property(name='black_region', property='Couplings:ThermalExpansion:Isotropic:a_black_region')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_black_region(alpha=5e-05, T0=0.0)
OOF.Material.Add_property(name='black_region', property='Couplings:ThermalExpansion:Isotropic:a_black_region')
OOF.Material.Assign(material='black_region', microstructure='grain.png', pixels='black_region')
OOF.Property.Copy(property='Color', new_name='colour_white_region')
OOF.Property.Parametrize.Color.colour_white_region(color=Gray(value=1.0))
OOF.Material.Add_property(name='white_region', property='Color:colour_white_region')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_white_region')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_white_region(cijkl=IsotropicRank4TensorEnu(young=100000000000.0,poisson=0.3))
OOF.Material.Add_property(name='white_region', property='Mechanical:Elasticity:Isotropic:youngs_white_region')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_white_region')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_white_region(kappa=100)
OOF.Material.Add_property(name='white_region', property='Thermal:Conductivity:Isotropic:k_white_region')
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_white_region')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_white_region(alpha=1e-05, T0=0.0)
OOF.Material.Add_property(name='white_region', property='Couplings:ThermalExpansion:Isotropic:a_white_region')
OOF.Material.Assign(material='white_region', microstructure='grain.png', pixels='white_region')
OOF.Skeleton.New(name='skeleton', microstructure='grain.png', x_elements=30, y_elements=30, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Skeleton.Modify(skeleton='grain.png:skeleton', modifier=Anneal(targets=AllNodes(),criterion=AverageEnergy(alpha=0.9),T=0.0,delta=1.0,iteration=FixedIteration(iterations=50)))
OOF.Skeleton.Modify(skeleton='grain.png:skeleton', modifier=SwapEdges(targets=AllElements(),criterion=AverageEnergy(alpha=0.9)))
OOF.Mesh.New(name='mesh', skeleton='grain.png:skeleton', element_types=['D2_2', 'T3_3', 'Q4_4'])
OOF.Subproblem.Field.Define(subproblem='grain.png:skeleton:mesh:default', field=Temperature)
OOF.Subproblem.Field.Activate(subproblem='grain.png:skeleton:mesh:default', field=Temperature)
OOF.Mesh.Field.In_Plane(mesh='grain.png:skeleton:mesh', field=Temperature)
OOF.Subproblem.Equation.Activate(subproblem='grain.png:skeleton:mesh:default', equation=Heat_Eqn)
OOF.Mesh.Boundary_Conditions.New(name='bc', mesh='grain.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=0.0),boundary='left'))
OOF.Mesh.Boundary_Conditions.New(name='bc<2>', mesh='grain.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=600.0),boundary='right'))
OOF.Subproblem.Set_Solver(subproblem='grain.png:skeleton:mesh:default', solver_mode=BasicSolverMode(time_stepper=BasicStaticDriver(),matrix_method=BasicIterative(tolerance=1e-13,max_iterations=1000)))
OOF.Mesh.Set_Field_Initializer(mesh='grain.png:skeleton:mesh', field=Temperature, initializer=ConstScalarFieldInit(value=0.1))
OOF.Mesh.Solve(mesh='grain.png:skeleton:mesh', endtime=0.0)
OOF.Graphics_1.Layer.Hide(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Show(n=0)
OOF.Graphics_1.Layer.Select(n=5)
OOF.LayerEditor.LayerSet.Edit(window='Graphics_1', layer_number=5)
OOF.LayerEditor.LayerSet.Add_Method(method=FilledContourDisplay(when=latest,what=getOutput('Field:Component',component='',field=Temperature),where=getOutput('original'),min=automatic,max=automatic,levels=11,nbins=5,colormap=ThermalMap()))
OOF.LayerEditor.LayerSet.Send(window='Graphics_1')
OOF.Graphics_1.File.Save_Contourmap(filename='/home/nanohub/srehman6/data/results/1643665/image', overwrite=False)
OOF.Graphics_1.File.Save_Image(filename='/home/nanohub/srehman6/data/results/1643665/image1', overwrite=False)
