OOF.Microstructure.Create_From_ImageFile(filename='/home/nanohub/srehman6/data/results/1643407/test.png', microstructure_name='test.png', height=automatic, width=automatic)
OOF.Windows.Graphics.New()
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='test.png:test.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(84.18,130.737333333)], shift=0, ctrl=0)
OOF.PixelGroup.New(name='black_region', microstructure='test.png')
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='test.png:test.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(5.068,42.532)], shift=0, ctrl=0)
OOF.PixelGroup.New(name='white_region', microstructure='test.png')
OOF.PixelGroup.AddSelection(microstructure='test.png', group='white_region')
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='test.png:test.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(80.5426666667,124.372)], shift=0, ctrl=0)
OOF.PixelGroup.AddSelection(microstructure='test.png', group='white_region')
OOF.PixelGroup.RemoveSelection(microstructure='test.png', group='white_region')
OOF.PixelGroup.AddSelection(microstructure='test.png', group='black_region')
OOF.Graphics_1.Toolbox.Pixel_Select.Color(source='test.png:test.png', range=DeltaRGB(delta_red=0,delta_green=0,delta_blue=0), points=[Point(18.708,128.009333333)], shift=0, ctrl=0)
OOF.Graphics_1.Toolbox.Pixel_Select.Circle(source='test.png:test.png', points=[Point(17.7986666667,128.918666667), Point(17.7986666667,128.918666667)], shift=0, ctrl=0)
OOF.Material.New(name='black_region', material_type='bulk')
OOF.Material.New(name='white_region', material_type='bulk')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_black_region')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_black_region(cijkl=IsotropicRank4TensorEnu(young=200000000000.0,poisson=0.3333333333333333))
OOF.Material.Add_property(name='black_region', property='Mechanical:Elasticity:Isotropic:youngs_black_region')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_black_region')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_black_region(kappa=300)
OOF.Material.Add_property(name='black_region', property='Thermal:Conductivity:Isotropic:k_black_region')
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_black_region')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_black_region(alpha=5e-05, T0=0.0)
OOF.Material.Add_property(name='black_region', property='Couplings:ThermalExpansion:Isotropic:a_black_region')
OOF.Property.Copy(property='Color', new_name='colour_black_region')
OOF.Property.Parametrize.Color.colour_black_region(color=Gray(value=0.0))
OOF.Material.Add_property(name='black_region', property='Color:colour_black_region')
OOF.Material.Assign(material='black_region', microstructure='test.png', pixels='black_region')
OOF.Property.Copy(property='Color', new_name='colour_white_region')
OOF.Property.Parametrize.Color.colour_white_region(color=Gray(value=1.0))
OOF.Material.Add_property(name='white_region', property='Color:colour_white_region')
OOF.Property.Copy(property='Mechanical:Elasticity:Isotropic', new_name='youngs_white_region')
OOF.Property.Parametrize.Mechanical.Elasticity.Isotropic.youngs_white_region(cijkl=IsotropicRank4TensorEnu(young=150000000000.0,poisson=0.27))
OOF.Material.Add_property(name='white_region', property='Mechanical:Elasticity:Isotropic:youngs_white_region')
OOF.Property.Copy(property='Thermal:Conductivity:Isotropic', new_name='k_white_region')
OOF.Property.Parametrize.Thermal.Conductivity.Isotropic.k_white_region(kappa=50)
OOF.Material.Add_property(name='white_region', property='Thermal:Conductivity:Isotropic:k_white_region')
OOF.Property.Copy(property='Couplings:ThermalExpansion:Isotropic', new_name='a_white_region')
OOF.Property.Parametrize.Couplings.ThermalExpansion.Isotropic.a_white_region(alpha=3e-05, T0=0.0)
OOF.Material.Add_property(name='white_region', property='Couplings:ThermalExpansion:Isotropic:a_white_region')
OOF.Material.Assign(material='white_region', microstructure='test.png', pixels='white_region')
OOF.Skeleton.New(name='skeleton', microstructure='test.png', x_elements=20, y_elements=20, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Skeleton.Modify(skeleton='test.png:skeleton', modifier=Anneal(targets=AllNodes(),criterion=AverageEnergy(alpha=0.9),T=0.0,delta=1.0,iteration=FixedIteration(iterations=100)))
OOF.Skeleton.Modify(skeleton='test.png:skeleton', modifier=SwapEdges(targets=AllElements(),criterion=AverageEnergy(alpha=0.8)))
OOF.Skeleton.Modify(skeleton='test.png:skeleton', modifier=Smooth(targets=AllNodes(),criterion=AverageEnergy(alpha=0.8),T=0.0,iteration=FixedIteration(iterations=50)))
OOF.Skeleton.Delete(skeleton='test.png:skeleton')
OOF.Skeleton.New(name='skeleton', microstructure='test.png', x_elements=50, y_elements=50, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Skeleton.Delete(skeleton='test.png:skeleton')
OOF.Skeleton.New(name='skeleton', microstructure='test.png', x_elements=10, y_elements=10, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Windows.Graphics.New()
OOF.Graphics_2.File.Close()
OOF.Graphics_1.File.Close()
OOF.Skeleton.Delete(skeleton='test.png:skeleton')
OOF.Skeleton.New(name='skeleton', microstructure='test.png', x_elements=50, y_elements=50, skeleton_geometry=QuadSkeleton(left_right_periodicity=False,top_bottom_periodicity=False))
OOF.Windows.Graphics.New()
OOF.Skeleton.Modify(skeleton='test.png:skeleton', modifier=Anneal(targets=AllNodes(),criterion=AverageEnergy(alpha=0.9),T=0.0,delta=1.0,iteration=FixedIteration(iterations=100)))
OOF.Skeleton.Modify(skeleton='test.png:skeleton', modifier=SwapEdges(targets=AllElements(),criterion=AverageEnergy(alpha=0.8)))
OOF.Skeleton.Modify(skeleton='test.png:skeleton', modifier=Smooth(targets=AllNodes(),criterion=AverageEnergy(alpha=0.8),T=0.0,iteration=FixedIteration(iterations=50)))
OOF.Mesh.New(name='mesh', skeleton='test.png:skeleton', element_types=['D2_2', 'T3_3', 'Q4_4'])
OOF.Subproblem.Field.Define(subproblem='test.png:skeleton:mesh:default', field=Temperature)
OOF.Subproblem.Field.Activate(subproblem='test.png:skeleton:mesh:default', field=Temperature)
OOF.Mesh.Field.In_Plane(mesh='test.png:skeleton:mesh', field=Temperature)
OOF.Subproblem.Equation.Activate(subproblem='test.png:skeleton:mesh:default', equation=Heat_Eqn)
OOF.Mesh.Boundary_Conditions.New(name='bc', mesh='test.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=450.0),boundary='right'))
OOF.Mesh.Boundary_Conditions.New(name='bc<2>', mesh='test.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=0.0),boundary='left'))
OOF.Mesh.Boundary_Conditions.New(name='bc<3>', mesh='test.png:skeleton:mesh', condition=DirichletBC(field=Temperature,field_component='',equation=Heat_Eqn,eqn_component='',profile=ConstantProfile(value=0.0),boundary='left'))
OOF.Mesh.Boundary_Conditions.Delete(mesh='test.png:skeleton:mesh', name='bc<3>')
OOF.Subproblem.Set_Solver(subproblem='test.png:skeleton:mesh:default', solver_mode=BasicSolverMode(time_stepper=BasicStaticDriver(),matrix_method=BasicIterative(tolerance=1e-13,max_iterations=1000)))
OOF.Mesh.Set_Field_Initializer(mesh='test.png:skeleton:mesh', field=Temperature, initializer=ConstScalarFieldInit(value=0.1))
OOF.Mesh.Solve(mesh='test.png:skeleton:mesh', endtime=0.0)
OOF.Graphics_1.Layer.Select(n=5)
OOF.LayerEditor.LayerSet.Edit(window='Graphics_1', layer_number=5)
OOF.LayerEditor.LayerSet.Add_Method(method=FilledContourDisplay(when=latest,what=getOutput('Field:Component',component='',field=Temperature),where=getOutput('original'),min=automatic,max=automatic,levels=11,nbins=5,colormap=ThermalMap()))
OOF.LayerEditor.LayerSet.Send(window='Graphics_1')
OOF.Graphics_1.Layer.Hide(n=5)
OOF.Graphics_1.Layer.Select(n=5)
OOF.Graphics_1.Layer.Hide(n=6)
OOF.Graphics_1.Layer.Select(n=6)
OOF.Graphics_1.Layer.Hide(n=1)
OOF.Graphics_1.Layer.Select(n=1)
OOF.Graphics_1.Layer.Show(n=1)
OOF.Graphics_1.Layer.Hide(n=0)
OOF.Graphics_1.Layer.Select(n=0)
OOF.Graphics_1.Layer.Show(n=0)
OOF.File.Save.Mesh(filename='/home/nanohub/srehman6/data/results/1643407/test.png', mode='w', format='ascii', mesh='test.png:skeleton:mesh')
OOF.Graphics_1.File.Save_Contourmap(filename='/home/nanohub/srehman6/data/results/1643407/contour.png', overwrite=False)
